export const countries = [
  {id: 1, value: 'Afghanistan', label: 'Afghanistan'},
  {id: 2, value: 'Albania', label: 'Albania'},
  {id: 3, value: 'Algeria', label: 'Algeria'},
  {id: 4, value: 'Andorra', label: 'Andorra'},
  {id: 5, value: 'Angola', label: 'Angola'},
  {id: 6, value: 'Antigua and Barbuda', label: 'Antigua and Barbuda'},
  {id: 7, value: 'Argentina', label: 'Argentina'},
  {id: 8, value: 'Armenia', label: 'Armenia'},
  {id: 9, value: 'Australia', label: 'Australia'},
  {id: 10, value: 'Austria', label: 'Austria'},
  {id: 11, value: 'Azerbaijan', label: 'Azerbaijan'},
  {id: 12, value: 'Bahamas', label: 'Bahamas'},
  {id: 13, value: 'Bahrain', label: 'Bahrain'},
  {id: 14, value: 'Bangladesh', label: 'Bangladesh'},
  {id: 15, value: 'Barbados', label: 'Barbados'},
  {id: 16, value: 'Belarus', label: 'Belarus'},
  {id: 17, value: 'Belgium', label: 'Belgium'},
  {id: 18, value: 'Belize', label: 'Belize'},
  {id: 19, value: 'Benin', label: 'Benin'},
  {id: 20, value: 'Bhutan', label: 'Bhutan'},
  {id: 21, value: 'Bolivia', label: 'Bolivia'},
  {id: 22, value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina'},
  {id: 23, value: 'Botswana', label: 'Botswana'},
  {id: 24, value: 'Brazil', label: 'Brazil'},
  {id: 25, value: 'Brunei', label: 'Brunei'},
  {id: 26, value: 'Bulgaria', label: 'Bulgaria'},
  {id: 27, value: 'Burkina Faso', label: 'Burkina Faso'},
  {id: 28, value: 'Burundi', label: 'Burundi'},
  {id: 29, value: 'Cabo Verde', label: 'Cabo Verde'},
  {id: 30, value: 'Cambodia', label: 'Cambodia'},
  {id: 31, value: 'Cameroon', label: 'Cameroon'},
  {id: 32, value: 'Canada', label: 'Canada'},
  {
    id: 33,
    value: 'Central African Republic',
    label: 'Central African Republic',
  },
  {id: 34, value: 'Chad', label: 'Chad'},
  {id: 35, value: 'Chile', label: 'Chile'},
  {id: 36, value: 'China', label: 'China'},
  {id: 37, value: 'Colombia', label: 'Colombia'},
  {id: 38, value: 'Comoros', label: 'Comoros'},
  {
    id: 39,
    value: 'Congo, Democratic Republic of the',
    label: 'Congo, Democratic Republic of the',
  },
  {id: 40, value: 'Congo, Republic of the', label: 'Congo, Republic of the'},
  {id: 41, value: 'Costa Rica', label: 'Costa Rica'},
  {id: 42, value: 'Croatia', label: 'Croatia'},
  {id: 43, value: 'Cuba', label: 'Cuba'},
  {id: 44, value: 'Cyprus', label: 'Cyprus'},
  {id: 45, value: 'Czech Republic', label: 'Czech Republic'},
  {id: 46, value: 'Denmark', label: 'Denmark'},
  {id: 47, value: 'Djibouti', label: 'Djibouti'},
  {id: 48, value: 'Dominica', label: 'Dominica'},
  {id: 49, value: 'Dominican Republic', label: 'Dominican Republic'},
  {id: 50, value: 'Ecuador', label: 'Ecuador'},
  {id: 51, value: 'Egypt', label: 'Egypt'},
  {id: 52, value: 'El Salvador', label: 'El Salvador'},
  {id: 53, value: 'Equatorial Guinea', label: 'Equatorial Guinea'},
  {id: 54, value: 'Eritrea', label: 'Eritrea'},
  {id: 55, value: 'Estonia', label: 'Estonia'},
  {id: 56, value: 'Eswatini', label: 'Eswatini'},
  {id: 57, value: 'Ethiopia', label: 'Ethiopia'},
  {id: 58, value: 'Fiji', label: 'Fiji'},
  {id: 59, value: 'Finland', label: 'Finland'},
  {id: 60, value: 'France', label: 'France'},
  {id: 61, value: 'Gabon', label: 'Gabon'},
  {id: 62, value: 'Gambia', label: 'Gambia'},
  {id: 63, value: 'Georgia', label: 'Georgia'},
  {id: 64, value: 'Germany', label: 'Germany'},
  {id: 65, value: 'Ghana', label: 'Ghana'},
  {id: 66, value: 'Greece', label: 'Greece'},
  {id: 67, value: 'Grenada', label: 'Grenada'},
  {id: 68, value: 'Guatemala', label: 'Guatemala'},
  {id: 69, value: 'Guinea', label: 'Guinea'},
  {id: 70, value: 'Guinea-Bissau', label: 'Guinea-Bissau'},
  {id: 71, value: 'Guyana', label: 'Guyana'},
  {id: 72, value: 'Haiti', label: 'Haiti'},
  {id: 73, value: 'Honduras', label: 'Honduras'},
  {id: 74, value: 'Hungary', label: 'Hungary'},
  {id: 75, value: 'Iceland', label: 'Iceland'},
  {id: 76, value: 'India', label: 'India'},
  {id: 77, value: 'Indonesia', label: 'Indonesia'},
  {id: 78, value: 'Iran', label: 'Iran'},
  {id: 79, value: 'Iraq', label: 'Iraq'},
  {id: 80, value: 'Ireland', label: 'Ireland'},
  {id: 81, value: 'Israel', label: 'Israel'},
  {id: 82, value: 'Italy', label: 'Italy'},
  {id: 83, value: 'Jamaica', label: 'Jamaica'},
  {id: 84, value: 'Japan', label: 'Japan'},
  {id: 85, value: 'Jordan', label: 'Jordan'},
  {id: 86, value: 'Kazakhstan', label: 'Kazakhstan'},
  {id: 87, value: 'Kenya', label: 'Kenya'},
  {id: 88, value: 'Kiribati', label: 'Kiribati'},
  {id: 89, value: 'Korea, North', label: 'Korea, North'},
  {id: 90, value: 'Korea, South', label: 'Korea, South'},
  {id: 91, value: 'Kuwait', label: 'Kuwait'},
  {id: 92, value: 'Kyrgyzstan', label: 'Kyrgyzstan'},
  {id: 93, value: 'Laos', label: 'Laos'},
  {id: 94, value: 'Latvia', label: 'Latvia'},
  {id: 95, value: 'Lebanon', label: 'Lebanon'},
  {id: 96, value: 'Lesotho', label: 'Lesotho'},
  {id: 97, value: 'Liberia', label: 'Liberia'},
  {id: 98, value: 'Libya', label: 'Libya'},
];
